Add validators for {imap,smtp,pop,nntp}_authenticators
neomutt/neomutt pull request #2624
Opened 2020-08-28 14:50 UTC by yousefakbar

* **What does this PR do?**

Adds validators to {imap,pop,smtp,nntp}_authenticators config variables. This also includes some refactoring of code in some files.

* **What are the relevant issue numbers?**

#2583 .

* **Things to Review**

Obviously the whole commit should be looked at for errors etc. but here are the key areas I would like input/confirmation on:

1. **Placement of function declarations**: `bool {imap,pop,smtp,nntp}_auth_is_valid()` functions are placed in .h files to make them visible to the validator functions. I just want to make sure they're not wandering in the wrong places :).

2. **Changes in `smtp/`**: Namely, I added a SmtpAuth multiplexor (similar to imap and pop's) and slightly modified `smtp_auth()` and `smtp_auth_sasl()`. I tested them and they work fine, but I want to emphasize the change and make sure it gets an okay.

3. **Changes in `nntp/`**: Most notably, I changed the nntp_authenticator config variable's data type to SLIST (was just string prev.) to mirror the other authenticators. This might have effects on the `nntp_auth()` backend (which needs an overhaul, anyway) that I was not able to test.

2020-08-29 23:18 UTC, flatcap commented
I've had a look through the code and it looks good -- it may take me a little while to review, though :-)

I noticed one bug, but not in your code, in mine!

If I `:set imap_authenticators="plain:plain"` then NeoMutt doesn't de-dupe the value.
If you have some time, please could you work on a fix for that.
(The `+=` code de-dupes, so you can probably cut'n'paste a little)

Thanks.

2020-08-30 11:03 UTC, yousefakbar commented
> it may take me a little while to review, though :-)

No rush at all :D.

> If you have some time, please could you work on a fix for that.

Sounds good! I'll work on that next.

2020-09-05 14:33 UTC, flatcap commented
I've merged the slist de-dupe and rebased over master.
Thanks.

2020-09-07 11:07 UTC, flatcap commented
I've had a think about SASL.
Please can you create an `sasl_auth_validator()` function in `conn/sasl.c`
It should check for all the possible Cyrus SASL authentication methods:
```
ANONYMOUS
CRAM-MD5
DIGEST-MD5
EXTERNAL
G2
GSSAPI
GSS-SPNEGO
KERBEROS_V4
LOGIN
NTLM
OTP
PASSDSS
PLAIN
SCRAM
SRP
```

We can then call this from the pop,imap,smtp,nntp validator functions.

Thanks.

2020-09-11 11:38 UTC, gahr commented on conn/sasl.c
> +};
I'd like the ARRAY APIs to be used instead of raw arrays whenever possible. See c24d17a99d16e81872f08f721a1793a57bbdaa92 for an example.

2020-09-11 11:49 UTC, gahr commented on conn/sasl.c
> +};
nevermind, disregard this :)

2020-09-11 13:27 UTC, flatcap commented
I've slightly refactored your validator functions, for clarity.
I've dropped the **specific** SASL error message and inverted the `if`s.

**Before**:
```c
STAILQ_FOREACH(np, &imap_auth_methods->head, entries)
{
  if (!imap_auth_is_valid(np->data))
  {
#ifdef USE_SASL
    if (!sasl_auth_validator(np->data))
    {
      mutt_buffer_printf(err, _("Option %s: %s invalid sasl authenticator"),
                         cdef->name, np->data);
      return CSR_ERR_INVALID;
    }
#else
    mutt_buffer_printf(err, _("Option %s: %s is not a valid authenticator"),
                       cdef->name, np->data);
    return CSR_ERR_INVALID;
#endif
  }
}
```

**After**:
```c
STAILQ_FOREACH(np, &imap_auth_methods->head, entries)
{
  if (imap_auth_is_valid(np->data))
    continue;
#ifdef USE_SASL
  if (sasl_auth_validator(np->data))
    continue;
#endif
  mutt_buffer_printf(err, _("Option %s: %s is not a valid authenticator"),
                     cdef->name, np->data);
  return CSR_ERR_INVALID;
}
```

2020-09-11 14:08 UTC, flatcap commented
I've split the changes into 5 commits: sasl, imap, pop, smtp and nntp.

2020-09-11 14:55 UTC, yousefakbar commented
Looks good to me 👍🏼 .

2020-09-11 19:38 UTC, gahr commented on conn/sasl.c
> +    if (auth && mutt_istr_equal(auth, authenticator))
Can `auth` ever be null?

2020-09-11 19:38 UTC, gahr commented on conn/sasl.c
> +static char *sasl_authenticators[] = {
static const char * const?

2020-09-11 19:38 UTC, gahr commented on conn/sasl.h
> +bool sasl_auth_validator(const char* authenticator);
`*` goes with the name, not the type

2020-09-11 19:38 UTC, gahr commented on nntp/nntp.c
> +static char *nntp_authenticators[] = { "user", "anonymous", "cram-md5", "gssapi", "sasl" };
`static const char * const`

2020-09-11 19:38 UTC, gahr commented on nntp/nntp.c
> +    if (auth && mutt_istr_equal(auth, authenticator))
Can `auth` ever be null?

2020-09-12 11:05 UTC, flatcap requested changes
I've found a problem with the SMTP changes; it's a little complicated to explain.

POP and IMAP follow the same pattern.

If `$auth_methods` is set, then:
- Loop through the user's `$auth_methods`
- Call the function `authenticate(data, name)`
  The SASL function **uses** the `name` parameter (most others ignore it)
- If one succeeds then we're finished

If `$auth_methods` isn't set, then:
- Loop through all the `auth_methods[]`
- Call the function `authenticate(data, NULL)`
  This time the SASL function uses a list of valid authentication methods which were obtained **from the server**
- If one succeeds then we're finished

---

In SMTP, the auth functions need an extra param (`name`).
- `smtp_auth_oauth()`, `smtp_auth_plain()`, `smtp_auth_sasl()`

In the first code block, we want to pass the name, telling SASL to use a **specific** method.
In the second code block, we'll pass `NULL` to let SASL negotiate a method (using `adata->auth_mechs`).

2020-09-29 13:10 UTC, flatcap approved these changes
I've removed the nntp changes.
They require a bit more research and enthusiasm than I can spare right now.

However the rest of the changes look great.
Thanks.

2020-09-29 13:12 UTC, merged

2020-10-30 21:35 UTC, Neustradamus commented
Thanks to @yousefakbar, @flatcap, @grawity about SCRAM:
- https://github.com/neomutt/neomutt/pull/2624 + https://github.com/neomutt/neomutt/commit/b7bcb9aef103943251305c05840cbe96c09a6508
- https://github.com/neomutt/neomutt/pull/2688 + https://github.com/neomutt/neomutt/commit/85437597de9e692fa8c0aeab7eaaf27e43c563c6

Linked to:
- https://github.com/neomutt/neomutt/issues/1846
- https://gitlab.com/muttmua/mutt/-/issues/174