Devel/matthugh/compose remove config variables
neomutt/neomutt pull request #2695
Opened 2020-10-10 20:14 UTC by matthewhughes934

* **What does this PR do?**

Removes global 'C_*' config variables from libcompose, replacing them with access to the corresponding ConfigSubset element.

* **Screenshots (if relevant)**

* **What are the relevant issue numbers?**

2622

2020-10-10 20:21 UTC, matthewhughes934 commented
Still want to do some deeper testing, I've manually test each added `cs_subset*` at least runs (i.e. I avoided any heinous typos), but still want to double check variables are respected (e.g. change the value of each). The only thing I missed (so far) in my testing is at `compose/compose.c:543` because I haven't played around enough with Newsgroups in Neomutt.

2020-10-11 00:10 UTC, flatcap commented
I've just added some `{}`s and moved a comment to keep the compiler happy.

2020-10-11 00:14 UTC, flatcap requested changes
Now we can eliminate the `C_*` variables completely (from compose),
and update the flags to `cs_register_variables()`
See: 6f79d959b2 for details.

2020-10-12 10:12 UTC, flatcap approved these changes

2020-10-12 10:13 UTC, merged