fix mut_buffer_alloc
neomutt/neomutt pull request #2783
Opened 2021-01-24 07:08 UTC by ngortheone

While working on https://github.com/neomutt/neomutt/pull/2782 I found some suspiciously looking things in `mutt_buffer_alloc()`

- #2782 expects Buffer to have non-NULL data after calling `mutt_buffer_alloc()` and explicitly passes a buffer with NULL data
- `mutt_buffer_alloc()` does not perform any checks if `buf->data == NULL` and does things like `buf->dptr = buf->data + offset;` 

I am not a C expert, but NULL + offset does not result in a valid memory address in my head.
I added a few more checks to be more defensive about edge cases.

2021-01-24 07:41 UTC, ngortheone commented
Failing test:
`Test test_mutt_buffer_add_printf...             realloc(): invalid next size`

2021-01-25 07:28 UTC, gahr commented
I don't see a bug in the code as it's currently written. Please can you read my comments and see if they answer your doubts.

2021-01-25 07:28 UTC, gahr requested changes

2021-01-25 07:28 UTC, gahr commented on mutt/buffer.c
> +    *(buf.dptr) = '\0';
`mutt_mem_calloc` initialized the memory to 0.

2021-01-25 07:28 UTC, gahr commented on mutt/buffer.c
> +  *(buf->dptr) = '\0';
`memset` sets the memory to 0

2021-01-25 07:28 UTC, gahr commented on mutt/buffer.c
> +  if (new_size <= 0)
`new_size` is an unsigned type, it cannot be negative.

2021-01-25 07:28 UTC, gahr commented on mutt/buffer.c
> -  if ((new_size > buf->dsize) || !buf->data)
here's the check on `buf->data == NULL` you're looking for...

2021-01-25 07:28 UTC, gahr commented on mutt/buffer.c
> -    size_t offset = (buf->dptr && buf->data) ? buf->dptr - buf->data : 0;
which results in offset being set to 0...

2021-01-25 07:28 UTC, gahr commented on mutt/buffer.c
> -    buf->dptr = buf->data + offset;
and `buf->dptr` being set to `buf->data`.

2021-01-25 16:31 UTC, closed without merging