notmuch: allow nm_record in non-notmuch mailboxes
neomutt/neomutt pull request #2818
Opened 2021-02-13 23:13 UTC by Austin-Ray

The 'nm_record' functionality doesn't work in non-notmuch mailboxes
because 'nm_record_message()' requires notmuch-specific account data.
Other mailbox types lack the data so 'nm_record_message()' fails.
NeoMutt's documentation does not limit this functionality to notmuch
mailboxes.

To improve behavior consistency and user experience, modify
'nm_record_message()' to access a default notmuch mailbox.
When a user sends an email from a non-notmuch mailbox, the notmuch
backend uses the default mailbox for database access to append the
message.

The backend does not FREE the default mailbox for two reasons:
1) The user may define it in their configuration.
2) For future calls to prevent repeated allocations/deallocations.

The code contains inline warnings repeating the above rationale for
future modifications to 'nm_record_message()'

Fixes #1867

2021-02-15 13:02 UTC, flatcap commented
@Austin-Ray 
Hello stranger ;-)

@neomutt/notmuch-users
Please can I have a second opinion from some Notmuch users.

Thanks

2021-02-15 13:35 UTC, jindraj commented
> @neomutt/notmuch-users
> Please can I have a second opinion from some Notmuch users.
I don't use `nm_record` because GMail automatically puts sent mail into [GMail]/Sent and it's fetched and labeled in next sync. Hopefully someone else uses it and will shed some light this value of this PR.

2021-02-20 18:03 UTC, Austin-Ray commented
I had hoped someone else would chime, but since no one else has.

I've been using `nm_record` as having NeoMutt add to the notmuch database when sending is more convenient than sending + pulling from mail provider or an external call to `notmuch new`. It's a better user experience for my workflow.

In addition, for new users, our documentation doesn't limit `nm_record` to notmuch mailboxes so to improve their experience, we should either enable functionality in non-notmuch mailboxes or update the docs calling out the limitation. 

Limiting to only notmuch mailboxes hampers our notmuch users who use its search integration, but not the `virtual-mailboxes`

2021-02-22 12:54 UTC, flatcap requested changes

2021-02-22 12:54 UTC, flatcap commented on notmuch/notmuch.c
> +static char *nm_get_default_url()
In C, `()` doesn't mean `(void)`

2021-02-22 12:54 UTC, flatcap commented on notmuch/notmuch.c
> +  char *url = mutt_mem_malloc(len);
We `alloc` the string here...

2021-02-22 12:54 UTC, flatcap commented on notmuch/notmuch.c
>    return nm_mdata_new(url);
... but nobody frees it.

2021-02-22 12:54 UTC, flatcap commented on notmuch/notmuch.c
> +    struct Mailbox *m = mx_path_resolve(default_url);
... nor here.

2021-02-22 12:54 UTC, flatcap commented on notmuch/notmuch.c
> +static struct Mailbox *get_default_mailbox()
`(void)`

2021-02-26 21:53 UTC, Austin-Ray commented on notmuch/notmuch.c
> +static struct Mailbox *get_default_mailbox()
Fixed

2021-02-26 21:53 UTC, Austin-Ray commented on notmuch/notmuch.c
> +static char *nm_get_default_url()
Fixed

2021-02-26 22:58 UTC, flatcap approved these changes
- clang-format'd
- rebased
- squashed

2021-02-26 23:10 UTC, merged