Add encryption and decryption pipes to arg parser
neomutt/neomutt pull request #3443
Opened 2022-06-20 15:18 UTC by holmanb

* **What does this PR do?**
allow use of oauth2 script without manual modification

* **Validation**
To validate the behavior works as expected, I inserted the following lines directly after then new variable assignments:
```
+print(ENCRYPTION_PIPE)
+print(DECRYPTION_PIPE)
+import os; os._exit(0)
```
note that `shlex` handles spaces in quoted arguments as one would expect in the output to test some inputs:
```
> ./mutt_oauth2.py userid@myschool.edu.tokens --verbose --test --encryption-pipe 'gpg --encrypt --recipient "me plus you"' --decrypt 'gpg --decrypt "another arg"'
['gpg', '--encrypt', '--recipient', 'me plus you']
['gpg', '--decrypt', 'another arg']
```
an email won't have spaces, but since this may be an arbitrary command, shlex is good hygiene.

alternatively, without args passed:
```
> ./mutt_oauth2.py userid@myschool.edu.tokens --verbose --test
['gpg', '--encrypt', '--recipient', 'YOUR_GPG_IDENTITY']
['gpg', '--decrypt']
```

* **Does this PR meet the acceptance criteria?** (This is just a reminder for you,
  this section can be removed if you fulfill it.)

   - Code follows the [style guide](https://neomutt.org/dev/code)
   
No mention of python that I see on this page, so I used best judgement, avoided additional dependencies, avoided new python3 features for broad compatibility, etc.

* **What are the relevant issue numbers?**

https://github.com/neomutt/neomutt/issues/3441

2022-06-21 13:39 UTC, brunnre8 commented on contrib/oauth2/mutt_oauth2.py
> +registrations['microsoft']['client_secret'] = args.microsoft_secret
Why do we need split flags? Client_id / client_secret should do no? Then just add a provider switch to pre populate the endpoints.

Also introducing options without a help seems somewhat bad form.

2022-06-21 20:48 UTC, holmanb commented
@brunnre8 Thanks for the review. I think I've addressed your comments.

2022-06-22 10:40 UTC, flatcap commented on contrib/oauth2/mutt_oauth2.py
> +    if args.client_id:
> If we don't care about backwards compatibility
> (i.e. users manually inserting their values into the script)

I think the answer's, 'No'.
Wherever we install the script, it's in a readonly location, so the user must be editing their own copy.

Your improvements mean that they can use it directly from the install.
**Future** updates would need to be backwards-compatible.

2022-06-22 10:47 UTC, flatcap commented on contrib/oauth2/mutt_oauth2.py
> +    if args.client_id:
> If we don't care about backwards compatibility
> (i.e. users manually inserting their values into the script)

I think the answer's, 'No'.
Wherever we install the script, it's in a readonly location, so the user must be editing their own copy.

Your improvements mean that they can use it directly from the install.
**Future** updates would need to be backwards-compatible.

2022-06-22 12:58 UTC, flatcap requested changes
Following your suggestion,
Please can you remove any references / conditions relating to a hard-coded GPG Id

2022-06-22 16:23 UTC, holmanb commented
> Following your suggestion, Please can you remove any references / conditions relating to a hard-coded GPG Id

Done.

The latest update to this PR is mostly argparsing changes, since I think I previously got all the references in the docs.

```./contrib/oauth2/mutt_oauth2.py -h
usage: mutt_oauth2.py [-h] [-v] [-d] [-a] [--authflow AUTHFLOW] [-t] [--decryption-pipe DECRYPTION_PIPE]
                      [--encryption-pipe ENCRYPTION_PIPE] [--client-id CLIENT_ID] [--client-secret CLIENT_SECRET]
                      [--provider {google,microsoft}]
                      tokenfile

positional arguments:
  tokenfile             persistent token storage

options:
  -h, --help            show this help message and exit
  -v, --verbose         increase verbosity
  -d, --debug           enable debug output
  -a, --authorize       manually authorize new tokens
  --authflow AUTHFLOW   authcode | localhostauthcode | devicecode
  -t, --test            test IMAP/POP/SMTP endpoints
  --decryption-pipe DECRYPTION_PIPE
                        decryption command (string), reads from stdin and writes to stdout, default: "gpg --decrypt"
  --encryption-pipe ENCRYPTION_PIPE
                        encryption command (string), reads from stdin and writes to stdout, suggested: "gpg
                        --encrypt --recipient YOUR_GPG_IDENTITY"
  --client-id CLIENT_ID
                        Provider id from registration
  --client-secret CLIENT_SECRET
                        (optional) Provider secret from registration
  --provider {google,microsoft}
                        Specify provider to use.

This script obtains and prints a valid OAuth2 access token. State is maintained in an encrypted TOKENFILE. Run with
"--verbose --authorize --encryption-pipe 'foo@bar.org'" to get started or whenever all tokens have expired,
optionally with "--authflow" to override the default authorization flow. To truly start over from scratch, first
delete TOKENFILE. Use "--verbose --test" to test the IMAP/POP/SMTP endpoints.
```

2022-06-23 09:11 UTC, flatcap commented
@brunnre8 Anything you'd like to add?
(your voice carries more weight than mine :-)

2022-06-23 21:18 UTC, merged

2022-06-30 20:07 UTC, tristancollins commented
Sorry for the quick, and likely not that useful, message here. I've spent a few hours trying to get the version of the mutt_oauth2.py script from the neomutt repo working (forced to look at alternate authentication methods as my O365 tenant seems to have started disallowing app passwords...) with no joy. Only when I replaced the neomutt version with the version from the mutt repo have things started working. I hadn't noticed the two versions were different as the date in the header was identical.

Anyway, it seems there is a bug in the updated parsing that forms the ENCRYPTION_PIPE. I'll take a further look over the weekend.

2022-06-30 21:03 UTC, holmanb commented
> when I replaced the neomutt version with the version from the mutt repo have things started working. I hadn't noticed the two versions were different

@tristancollins - What value are you setting for the `--encryption-pipe` arg?