stuct Address: replace char * uses with struct Buffer
neomutt/neomutt pull request #3799
Opened 2023-04-03 12:57 UTC by navi-desu

This marks the beginning of the adventure to replace the uses of raw C pointers with buffers.

* **What does this PR do?**
Replaces the char * in the struct Address with struct Buffer *

2023-04-03 13:19 UTC, navi-desu commented on address/address.c
> +  mutt_buffer_copy(p->mailbox, addr->mailbox);
Indeed

2023-05-18 13:35 UTC, flatcap requested changes
Sorry it's taken a while to work through this.
I've done a bit of light tidying as I reviewed.

There are three things I'd like fixed, please:
- Simplify `buf_dequote_comment()`
- Make the `rfc2047_encode()` and `rfc2047_decode()` calls safe
- Add tests for the 12 new Buffer functions that you've introduced

Thanks!

2023-05-18 13:35 UTC, flatcap commented on mutt/buffer.c
> +  FREE(&tmp);
I don't think we need to dupe the string, here.
`mutt_str_dequote_comment()` only ever shortens the string, so we should be safe.
After calling it, we should call `buf_fix_dptr()` to adjust the end marker.

2023-05-18 13:35 UTC, flatcap commented on email/rfc2047.c
> +      rfc2047_encode(&a->personal->data, AddressSpecials, col, c_send_charset);
this...

2023-05-18 13:35 UTC, flatcap commented on email/rfc2047.c
> +      rfc2047_encode(&a->mailbox->data, AddressSpecials, col, c_send_charset);
this...

2023-05-18 13:35 UTC, flatcap commented on email/rfc2047.c
> +      rfc2047_decode(&a->personal->data);
this...

2023-05-18 13:35 UTC, flatcap commented on email/rfc2047.c
> +      rfc2047_decode(&a->mailbox->data);
and this are actually dangerous, but it's subtle.

`rfc2047_encode()` and `rfc2047_decode()` replace the original string with a newly allocated one.
This means that `Buffer.data` is changed, `Buffer.dsize` is wrong and `Buffer.dptr` is now dangling!

It's a bit messy, but I think the only safe thing to do is do dupe the string, encode/decode it, then overwrite the original Buffer.

2023-05-27 11:09 UTC, flatcap commented
ping?

2023-06-03 19:03 UTC, flatcap approved these changes
Nice work.  Thanks!

2023-06-03 19:13 UTC, merged