Devel/color colorschemes
neomutt/neomutt pull request #3871
Opened 2023-05-21 05:40 UTC by rayfordshire

* **What does this PR do?**

  - Use "bold" attribute and "light" prefix instead of "bright" prefix
  - Split the parsing logic for different colour syntaxes ("#RRGGBB", "colorNNN", named colour) into separate functions.

* **What are the relevant issue numbers?**

#3855

* **Remark:**

Currently, these internal parser functions abuse `MUTT_CMD_WARNING` to indicate they failed parsing and a different syntax should be used.  It may, or may not be cleaner to introduce a new command result, e.g. `MUTT_CMD_RETRY` or `MUTT_CMD_CONTINUE`, which indicates that the next parsing method should be tried on the same input data.  Alternatively, those methods could take an additional argument `enum CommandResult *ret` which they write their command result to and use the return value of the function to indicate "I handled it"/"next syntax should get a try".

2023-05-21 16:00 UTC, flatcap requested changes
> Split the parsing logic for different colour syntaxes

Good call!

> parser functions abuse MUTT_CMD_WARNING to indicate they failed parsing and a different syntax should be used.

That seems OK.

I've updated the Doxygen header to spell out all the possible retvals.

One other change, I've renamed `parse_color_colorNNN()` to `parse_color_colornnn()` for consistency.
(all functions are currently `[a-z0-9_]+`)

The only thing I'm not _entirely_ happy with is the duplication of the prefix parsing ("bright", ...).
If you could factor _that_ out, it'd be perfect.

Thanks

2023-05-21 16:29 UTC, rayfordshire commented
> The only thing I'm not entirely happy with is the duplication of the prefix parsing ("bright", ...).
> If you could factor that out, it'd be perfect.

Not entirely sure what you mean.  Do you mean splitting out a method:
```
void parse_prefix(const char *s, uint32_t *col, int *attrs,
                  bool is_fg, struct Buffer *err,
                  bool *bright_out, bool *light_out, bool *alert_out)
```
?  That seems ugly, due to the three return values.

2023-05-21 17:22 UTC, flatcap commented
yeah

Could we pass out the combined result in `int *attr` -- merging `A_BOLD | ...`
Something like:

`int parse_prefix(const char *str, int *attr)`

that returns the prefix length.

Maybe :-)

If it still looks ugly, we'll just leave the code as it is.

2023-05-26 12:00 UTC, flatcap approved these changes
That'll do nicely.
Thanks!

2023-05-26 12:00 UTC, merged