Fix '%{...}' expando
neomutt/neomutt pull request #4341
Opened 2024-07-02 08:23 UTC by gahr

Fixes #4335

2024-07-02 11:58 UTC, g0mb4 requested changes
I like this solution better. The results are compared with v20230517, and they are the same (except for multiple `%Z`s).

2024-07-02 11:58 UTC, g0mb4 commented on hdrline.c
> +  char *bigz = strstr(tmp2, "%Z");
We should handle the case when multiple `%Z`s are present (to be fully compatible with the old parser)

2024-07-02 12:27 UTC, g0mb4 commented
Ohh, `$index_format`'s`%d` (`index_d`) can be buggy if `$date_format` contains a `%z` or `%Z`.  It is the same problem.

2024-07-02 12:30 UTC, gahr commented
> Ohh, `$index_format`'s`%d` (`index_d`) can be buggy if `$date_format` contains a `%z` or `%Z`. It is the same problem.

Yeah - most of the code is duplicated. Let me refactor it.

2024-07-02 13:34 UTC, g0mb4 commented
The output is correct, tested with:

```
color index_date yellow blue
set date_format = "%H:%M %z %Z %Z"
set index_format = "%(%H:%M) - %[%H:%M] - %{%H:%M %z %Z %Z} - %d"
```

but  it leaks.

```
==164185==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 150 byte(s) in 10 object(s) allocated from:
    #0 0x7a4a3f0b4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x5ad9d158e836 in mutt_mem_malloc mutt/memory.c:96
    #2 0x5ad9d159f16c in mutt_strn_dup mutt/string.c:385
    #3 0x5ad9d111f549 in index_email_date /home/gmb/prog/neomutt/neomutt/hdrline.c:355
    #4 0x5ad9d1121844 in index_d /home/gmb/prog/neomutt/neomutt/hdrline.c:692
    #5 0x5ad9d14e4c66 in node_expando_render expando/node_expando.c:355
    #6 0x5ad9d14e923a in node_render expando/render.c:55
    #7 0x5ad9d14ddfe0 in expando_render expando/expando.c:119
    #8 0x5ad9d14defa5 in expando_filter expando/filter.c:154
    #9 0x5ad9d1129a20 in mutt_make_string /home/gmb/prog/neomutt/neomutt/hdrline.c:1748
    #10 0x5ad9d11a82f6 in index_make_entry index/dlg_index.c:891
    #11 0x5ad9d135d14a in menu_redraw_index menu/draw.c:338
    #12 0x5ad9d11c8ecd in index_repaint index/index.c:629
    #13 0x5ad9d1307a38 in window_repaint gui/mutt_window.c:598
    #14 0x5ad9d1307aea in window_repaint gui/mutt_window.c:604
    #15 0x5ad9d1307aea in window_repaint gui/mutt_window.c:604
    #16 0x5ad9d1307aea in window_repaint gui/mutt_window.c:604
    #17 0x5ad9d1307aea in window_repaint gui/mutt_window.c:604
    #18 0x5ad9d1307aea in window_repaint gui/mutt_window.c:604
    #19 0x5ad9d1307d05 in window_redraw gui/mutt_window.c:642
    #20 0x5ad9d11ab9d7 in dlg_index index/dlg_index.c:1242
    #21 0x5ad9d114cdc1 in main /home/gmb/prog/neomutt/neomutt/main.c:1432
    #22 0x7a4a3ea29d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Direct leak of 150 byte(s) in 10 object(s) allocated from:
    #0 0x7a4a3f0b4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x5ad9d158e836 in mutt_mem_malloc mutt/memory.c:96
    #2 0x5ad9d159f16c in mutt_strn_dup mutt/string.c:385
    #3 0x5ad9d111f549 in index_email_date /home/gmb/prog/neomutt/neomutt/hdrline.c:355
    #4 0x5ad9d111fda8 in index_date /home/gmb/prog/neomutt/neomutt/hdrline.c:462
    #5 0x5ad9d14e4c66 in node_expando_render expando/node_expando.c:355
    #6 0x5ad9d14e923a in node_render expando/render.c:55
    #7 0x5ad9d14ddfe0 in expando_render expando/expando.c:119
    #8 0x5ad9d14defa5 in expando_filter expando/filter.c:154
    #9 0x5ad9d1129a20 in mutt_make_string /home/gmb/prog/neomutt/neomutt/hdrline.c:1748
    #10 0x5ad9d11a82f6 in index_make_entry index/dlg_index.c:891
    #11 0x5ad9d135d14a in menu_redraw_index menu/draw.c:338
    #12 0x5ad9d11c8ecd in index_repaint index/index.c:629
    #13 0x5ad9d1307a38 in window_repaint gui/mutt_window.c:598
    #14 0x5ad9d1307aea in window_repaint gui/mutt_window.c:604
    #15 0x5ad9d1307aea in window_repaint gui/mutt_window.c:604
    #16 0x5ad9d1307aea in window_repaint gui/mutt_window.c:604
    #17 0x5ad9d1307aea in window_repaint gui/mutt_window.c:604
    #18 0x5ad9d1307aea in window_repaint gui/mutt_window.c:604
    #19 0x5ad9d1307d05 in window_redraw gui/mutt_window.c:642
    #20 0x5ad9d11ab9d7 in dlg_index index/dlg_index.c:1242
    #21 0x5ad9d114cdc1 in main /home/gmb/prog/neomutt/neomutt/main.c:1432
    #22 0x7a4a3ea29d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Direct leak of 60 byte(s) in 10 object(s) allocated from:
    #0 0x7a4a3f0b4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x5ad9d158e836 in mutt_mem_malloc mutt/memory.c:96
    #2 0x5ad9d159f16c in mutt_strn_dup mutt/string.c:385
    #3 0x5ad9d111f549 in index_email_date /home/gmb/prog/neomutt/neomutt/hdrline.c:355
    #4 0x5ad9d111fbb1 in index_date_local /home/gmb/prog/neomutt/neomutt/hdrline.c:432
    #5 0x5ad9d14e4c66 in node_expando_render expando/node_expando.c:355
    #6 0x5ad9d14e923a in node_render expando/render.c:55
    #7 0x5ad9d14ddfe0 in expando_render expando/expando.c:119
    #8 0x5ad9d14defa5 in expando_filter expando/filter.c:154
    #9 0x5ad9d1129a20 in mutt_make_string /home/gmb/prog/neomutt/neomutt/hdrline.c:1748
    #10 0x5ad9d11a82f6 in index_make_entry index/dlg_index.c:891
    #11 0x5ad9d135d14a in menu_redraw_index menu/draw.c:338
    #12 0x5ad9d11c8ecd in index_repaint index/index.c:629
    #13 0x5ad9d1307a38 in window_repaint gui/mutt_window.c:598
    #14 0x5ad9d1307aea in window_repaint gui/mutt_window.c:604
    #15 0x5ad9d1307aea in window_repaint gui/mutt_window.c:604
    #16 0x5ad9d1307aea in window_repaint gui/mutt_window.c:604
    #17 0x5ad9d1307aea in window_repaint gui/mutt_window.c:604
    #18 0x5ad9d1307aea in window_repaint gui/mutt_window.c:604
    #19 0x5ad9d1307d05 in window_redraw gui/mutt_window.c:642
    #20 0x5ad9d11ab9d7 in dlg_index index/dlg_index.c:1242
    #21 0x5ad9d114cdc1 in main /home/gmb/prog/neomutt/neomutt/main.c:1432
    #22 0x7a4a3ea29d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Direct leak of 60 byte(s) in 10 object(s) allocated from:
    #0 0x7a4a3f0b4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x5ad9d158e836 in mutt_mem_malloc mutt/memory.c:96
    #2 0x5ad9d159f16c in mutt_strn_dup mutt/string.c:385
    #3 0x5ad9d111f549 in index_email_date /home/gmb/prog/neomutt/neomutt/hdrline.c:355
    #4 0x5ad9d111f9ba in index_date_recv_local /home/gmb/prog/neomutt/neomutt/hdrline.c:402
    #5 0x5ad9d14e4c66 in node_expando_render expando/node_expando.c:355
    #6 0x5ad9d14e923a in node_render expando/render.c:55
    #7 0x5ad9d14ddfe0 in expando_render expando/expando.c:119
    #8 0x5ad9d14defa5 in expando_filter expando/filter.c:154
    #9 0x5ad9d1129a20 in mutt_make_string /home/gmb/prog/neomutt/neomutt/hdrline.c:1748
    #10 0x5ad9d11a82f6 in index_make_entry index/dlg_index.c:891
    #11 0x5ad9d135d14a in menu_redraw_index menu/draw.c:338
    #12 0x5ad9d11c8ecd in index_repaint index/index.c:629
    #13 0x5ad9d1307a38 in window_repaint gui/mutt_window.c:598
    #14 0x5ad9d1307aea in window_repaint gui/mutt_window.c:604
    #15 0x5ad9d1307aea in window_repaint gui/mutt_window.c:604
    #16 0x5ad9d1307aea in window_repaint gui/mutt_window.c:604
    #17 0x5ad9d1307aea in window_repaint gui/mutt_window.c:604
    #18 0x5ad9d1307aea in window_repaint gui/mutt_window.c:604
    #19 0x5ad9d1307d05 in window_redraw gui/mutt_window.c:642
    #20 0x5ad9d11ab9d7 in dlg_index index/dlg_index.c:1242
    #21 0x5ad9d114cdc1 in main /home/gmb/prog/neomutt/neomutt/main.c:1432
    #22 0x7a4a3ea29d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

SUMMARY: AddressSanitizer: 420 byte(s) leaked in 40 allocation(s).
```

2024-07-02 13:49 UTC, gahr commented
ah sure, my bad - forgot to free the temporary.

2024-07-02 13:55 UTC, g0mb4 commented
Works.

2024-07-02 14:08 UTC, g0mb4 approved these changes

2024-07-04 11:45 UTC, gahr commented
> Can we add a test for this?

Good question, I have very limited familiarity with the expando machinery. @g0mb4 how hard would it be to add a unit test for this?

2024-07-04 15:32 UTC, g0mb4 commented
Well, I have to refresh my memory on the tests (I created them to test the expando library, not a specific expando that Neomutt uses), but I think it is possible. I can create the test in a couple of days if that is okay.

2024-07-09 11:05 UTC, g0mb4 commented
I'm afraid that there is no easy way to test this. I see two options:

1.  Copy/Paste the expando callback and test that. This way, we have to manually sync the callbacks.
2.  Use the callback NeoMutt uses.  This would require linking a lot of the `.o` files from NeoMutt.... (there are a *LOT* of stubs to prevent that)

Any opinions?

2024-07-09 11:17 UTC, g0mb4 commented
3. Wilder idea: Run neomutt with a specific `.rc` file against a test mailbox, redirect the output into a file, and compare it against a golden file.

2024-07-09 11:21 UTC, roccoblues commented
I'm probably missing something but why can't we write unit tests for the `index_email_date` function? Is that what you mean with: 

>     2. Use the callback NeoMutt uses.  This would require linking a lot of the `.o` files from NeoMutt.... (there are a _LOT_ of stubs to prevent that)

?

2024-07-09 11:54 UTC, g0mb4 commented
Yep, but if we can test one callback, we are able to test all of them, but the required information on how to parse/render an expando is not part of `libexpando`. If we truly want to test them we have to use the same parameters as NeoMutt.

2024-07-09 12:10 UTC, gahr commented
Alright - I'd rather merge this anyway: @roccoblues ack?

2024-07-09 12:41 UTC, roccoblues approved these changes

2024-07-09 12:55 UTC, merged